# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ron Boger
# tagline:             'personal site + musings'
tagline:             ''
description:         'Writings, projects, and more'
url:                 http://ronboger.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ron Boger
  url:               https://ronboger.github.io
  email:             ronnyb@jhu.edu

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 2
paginate_path: "page:num"
